### ISSUE TITLE
Feature: Debugger

### ISSUE THREAD

**Issue by svoop** [nova-ruby/rails#11]
Nova 9 features [debugger support](https://library.panic.com/nova/debugging/). 👍 But there's no built-in support for Ruby. 😢

Given this excellent extension is the de-facto standard for Ruby, any chance you might [add a debugging adapter for Ruby](https://docs.nova.app/extensions/debug-adapters/)?

Luckily, Ruby has the resurrected [debug](https://rubygems.org/gems/debug) bundled by default these days, support for other debugger gems such as byebug won't be necessary IMO.

**Comment by svoop** [comment]
@tommasongr Sure thing. I'm a little inundated by other OOS projects and won't be able to contribute much code, but you can count on me for testing. By the way, don't bother with byebug, the future of Ruby debugging lies quite likely with debug.

**Comment by tommasongr** [comment]
Quick follow-up.

The other day I asked the Panic team about the missing Ruby debugger.
As you can see [here](https://twitter.com/tommasongr/status/1504983443909849090?s=20&t=sjDZYMFlevZTD932U8YbqQ) they said that they would like to officially support it! The fact that is missing right now is a matter of lack of time in the previous release cycle.

IMO an official support would be much better than adding it to the extension. So I decided to wait and see how the situation evolves. I hope you agree.

**Comment by svoop** [comment]
This response from Panic certainly sounds more enthusiastic than the one when I asked a couple of months ago. The rap then was more along the lines of: We'll provider the API for it. So let's be patient for now,  but I hope this won't take forever. The last few releases have been pretty disappointing for me, not a single feature had any impact on my workflows. And knowing the editor handles debuggers just not the excellent Ruby debug gem is almost worse than having no debugger support at all. :-)

**Comment by tommasongr** [comment]
I get your disappointment for the last two majors. I'm not a big VIM or debugger enthusiast too. However I should say that the overall nova experience has become way more stable in the past few releases. I haven't experienced a single crash in months, that's a big achievement for me.

Anyway I'm working on a small release for nova-rails which is going to remove the default rails server task and instead will provide some additional ones as tasks templates. This way it would be easier to support both the old `bin/rails server` command and the new `bin/dev`. I'm also considering adding a template for bridgetownrb commands like start, build and clean. I know is not purely rails but in the context of wider ruby environment it might make sense. So if you haven't had much out of the past Nova releases, perhaps these can be appreciated goodies 😉

If you or somebody else are interested in discussing the changes above I'll open a PR in the coming days.

**Comment by svoop** [comment]
Update from Panic: Didn't make version 10, hopefully 11.

**Comment by tommasongr** [comment]
Yep... Right now I'm in the process of making a major update for my other extension (Vue), after that I hope I can spend some time on this one and see what we can do about it.

**Comment by tommasongr** [comment]
@svoop Ruby Debugger is coming soon... very soon 😉 Stay tuned I'll need some help to test it out!

**Comment by svoop** [comment]
@tommasongr

Wrapping it in a new extension makes a lot of sense, also to signal that native support is the ultimate goal since it's such an essential feature for a code editor – and you don't want to spend the rest of your days fixing what's broken after every Nova update. 

Thanks so much for having a go at this even though its life will hopefully be short!

> 3. Not bloating this extension...

Couldn't agree more! A one stop extension focusing on Rails is problematic. Ruby ≠ Rails and there are great other foundations such as Hanami, Roda, Bridgetown etc. Much of what a Rails extension brings to the table is mere clutter for any other Ruby project.

By the way, there are already parts of your Rails ext which would make for great extensions of their own: Solagraph and Rubocop. 

As for testing, I'll be happy to!

**Comment by eirvandelden** [comment]
That's great to hear you had time to focus work on Debugger support. Tag me when you are ready for testers, I'll help as much as I can :)

**Comment by tommasongr** [comment]
> By the way, there are already parts of your Rails ext which would make for great extensions of their own: Solagraph and Rubocop.

Yep, that's another topic... Since I'm messing around with [ruby-lsp](https://github.com/Shopify/ruby-lsp) I was wondering if having both LSPs in a single extension would make sense. Right now I've not been able to get it working but in the future we may have to choose what to keep and what to leave.

**Comment by svoop** [comment]
> Since I'm messing around with [ruby-lsp](https://github.com/Shopify/ruby-lsp) I was wondering if having both LSPs in a single extension would make sense.

IMO it does, yes, provided you can enable/disable each supported LSP individually.

(However, I haven't had much luck with such features in the past though since I'm using `direnv` to switch Rubies and this never played nice with such extensions in Atom or VS Code, so I'm not really an authority on this one. 😄 )

**Comment by svoop** [comment]
> By the way if someone is interested in ruby-lsp I would love to get some help. I'm kinda at a roadblock and I'm not sure what's the problem.

I doubt to be much help, but never say never... is there an issue on where you're stuck?

**Comment by tommasongr** [comment]
@svoop @eirvandelden

We have a debugger! https://github.com/tommasongr/nova-ruby-debug

You can search for Ruby Debug in the extension library!

I opened a discussion on the new repo to gather all your feedback and impressions: https://github.com/tommasongr/nova-ruby-debug/discussions/1

---

@svoop you will be happy to know that the extension already honors both `Gemfile` and `gems.rb` 😆. Since you reported the issue both here and in bridgetown I assume is something you care a lot about 😂😉
